# Generated by Django 4.2.1 on 2023-06-12 08:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_meep'),
    ]

    operations = [
        migrations.AddField(
            model_name='meep',
            name='body',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='meep',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
